#!/bin/bash -eu

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

clj -m cljs.main --target node --output-to ice-plugin.js -c ice.core

mkdir -p ~/.config/nvim/rplugin/node
ln -sfv $BASE/ice-plugin.js ~/.config/nvim/rplugin/node/ice-plugin.js
# ln -sfv $BASE/ice-plugin.js ~/.config/nvim/rplugin/node/index.js

ln -sfv $BASE/out ~/.config/nvim/rplugin/node/out
